<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Debug;Release;Production</Configurations>

        <Version>1.7.0</Version>
        <AssemblyVersion>1.7.0</AssemblyVersion>
        <FileVersion>1.7.0</FileVersion>
        <InformationalVersion>1.7.0</InformationalVersion>
    </PropertyGroup>
</Project>
